import = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 17 }
dynamic_padding = true
decorations = "Transparent"
opacity = 0.95
blur = true
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 5

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12
